let currentStudent = null;

function submitProfile() {
  const data = {
    primaryDirectorate: document.getElementById("primaryDoctorate").value,
    currentSchool: document.getElementById("currentSchool").value,
    currentGpa: document.getElementById("currentGpa").value,
    currentGrade: document.getElementById("currentGrade").value,
    eightGradeSchool: document.getElementById("eightGradeSchool").value,
    email: document.getElementById("email").value,
    cellPhone: document.getElementById("cellPhone").value,
    homePhone: document.getElementById("homePhone").value,
    address: document.getElementById("address").value,
    birthDate: document.getElementById("birthDate").value,
    gender: document.getElementById("gender").value,
    ethnicity: document.getElementById("ethnicity").value,
    dietaryRestrictions: document.getElementById("dietaryRestrictions").value,
    studentConsent: document.getElementById("studentConsent").value,
    parent1Name: document.getElementById("parent1Name").value,
    parent2Name: document.getElementById("parent2Name").value,
    parent1Email: document.getElementById("parent1Email").value,
    parent2Email: document.getElementById("parent2Email").value,
    parent1Phone: document.getElementById("parent1Phone").value,
    parent1Consent: document.getElementById("parent1Consent").value,
    parent2Consent: document.getElementById("parent2Consent").value,
  };

  console.log(data);
  return false;
}

function pageSetup() {
  currentStudent = studentData[4];
  document.getElementById("userFirstName").innerHTML = currentStudent.name;
}

const announcements = [
  {
    name: "Aaron Tostado",
    date: "Thursday, August 20",
    time: " 11:27 AM ",
    content: `Hi Team! Here is our quad chart for Week 1! Find your name and follow our
    example. These will be due every Sunday night at 8pm, unless we specify
    something different in the future. `,
  },
  {
    name: "Joy Uehara ",
    date: "Monday, August 17",
    time: " 8:16 PM",
    content: `Reminder that there are no directorate meetings or trainings this week. You
    are still required to attend the Tuesday meeting which is now from 6PM -
    8PM. There is no hours requirement for the week`,
  },
  {
    name: "Fazlul Zubair",
    date: "Monday, August 10",
    time: " 11:18 PM ",
    content: `Hello Everyone!
    It has been a while since our last update, so here goes:
    1) INFINITE RECHARGE - Part II
    For those who have not seen the announcement, next year Infinite Recharge
    will be back! We will be playing the same game with some rule updates (yet
    to be released). Due to this, we are officially kicking off our 2021 season
    now! This will include updates to our team handbook and expectations
    (more to follow soon)!
    2) Meeting Attendance is Mandatory!
    If you are a student member who is planning to return to the team next
    year, your attendance at our Tuesday meetings are mandatory going forward
    (starting 5/26). In a normal year we would have 12 hours of meetings a
    week, we are now down to 1 hour on Tuesday + Directorate level meetings,
    so everyone should be able to meet this commitment. Attendance will be
    tracked!
    3) Welcome 2021 Directors!
    Our new leadership team is starting the transition to the 2021 season. Thank
    you to our exiting team as they help the new leaders on board!
    4) Booster Bot Meeting - Tuesday, June 9th @ 8 PM
    Now that we have some idea of what next year will look like, we would like
    to let parents and boosters know about some of the changes in expectations
    for next year. The main topics will be:
    2021 Season Outlook `,
  },
];

const events = [
  {
    title: "Team Meeting",
    date: "September 1, 2020",
    time: "6:00 PM - 8;00 PM",
    location: "Zoom",
  },
  {
    title: "Team Meeting",
    date: "September 6, 2020",
    time: "2:00 PM - 7:00 PM",
    location: "Zoom",
  },
  {
    title: "Leadership Meeting",
    date: "September 6, 2020",
    time: "7:00 PM - 8:00 PM",
    location: "Zoom",
  },
  {
    title: "Rookie Bot CAD Session",
    date: "September 7, 2020",
    time: "5:00 PM - 6:00 PM",
    location: "Zoom",
  },
  {
    title: "Director Meeting",
    date: "September 8, 2020",
    time: "6:00 PM - 9:00 PM",
    location: "Zoom",
  },
];

const studentData = [
  {
    _id: 1,
    name: "Nicky MacIlwrick",
    current_school: "Royal Holloway and Bedford New College",
    current_grade: 2,
    current_gpa: 3.48,
    eigth_grade_school: "flexibility",
    personal_email: "nmacilwrick0@biblegateway.com",
    cell_phone: "850-711-1158",
    home_phone: "626-924-1897",
    street: "2522 Jenna Place",
    city: "Pensacola",
    state: "Florida",
    zipcode: "32520",
    birthdate: "7/21/1992",
    gender: "Male",
    race: "Cree",
    ethnicity: "Shoshone",
    student_consent: true,
    dietary_restrictions: null,
    health_restrictions: null,
    parent_one: {
      name: "Christoforo Shortall",
      phone: "205-680-6374",
      email: "cshortall0@cdbaby.com",
      consent: true,
    },
    parent_two: null,
    account_type: "Student",
    access_type: "Normal",
    student: true,
  },
  {
    _id: 2,
    name: "Gan Jachimak",
    current_school: "Omsk State University",
    current_grade: 5,
    current_gpa: 1.16,
    eigth_grade_school: "demand-driven",
    personal_email: "gjachimak1@samsung.com",
    cell_phone: "334-672-2374",
    home_phone: "559-514-9542",
    street: "9 Luster Avenue",
    city: "Montgomery",
    state: "Alabama",
    zipcode: "36177",
    birthdate: "8/9/1993",
    gender: "Male",
    race: "South American",
    ethnicity: "Venezuelan",
    student_consent: true,
    dietary_restrictions: null,
    health_restrictions: "Quetiapine fumarate",
    parent_one: {
      name: "Christoforo Shortall",
      phone: "205-680-6374",
      email: "cshortall0@cdbaby.com",
      consent: true,
    },
    parent_two: null,
    student: true,
  },
  {
    _id: 3,
    name: "Hollyanne Aguirre",
    current_school: "University of Aizu",
    current_grade: 3,
    current_gpa: 1.99,
    eigth_grade_school: "protocol",
    personal_email: "haguirre2@edublogs.org",
    cell_phone: "212-952-5693",
    home_phone: "801-527-4613",
    street: "1 Lake View Court",
    city: "New York City",
    state: "New York",
    zipcode: "10009",
    birthdate: "1/24/1996",
    gender: "Female",
    race: "Yakama",
    ethnicity: "Costa Rican",
    student_consent: true,
    dietary_restrictions: null,
    health_restrictions: "Proactiv",
    parent_one: {
      name: "Christoforo Shortall",
      phone: "205-680-6374",
      email: "cshortall0@cdbaby.com",
      consent: true,
    },
    parent_two: null,
    student: true,
  },
  {
    _id: 4,
    name: "Kasey Goscomb",
    current_school: "Hamdard University",
    current_grade: 2,
    current_gpa: 2.29,
    eigth_grade_school: "Horizontal",
    personal_email: "kgoscomb3@unblog.fr",
    cell_phone: "952-282-8965",
    home_phone: "716-947-2690",
    street: "21 Bultman Parkway",
    city: "Young America",
    state: "Minnesota",
    zipcode: "55551",
    birthdate: "12/6/1994",
    gender: "Female",
    race: "Comanche",
    ethnicity: "Spaniard",
    student_consent: true,
    dietary_restrictions: "Nausea Constipation",
    health_restrictions: null,
    parent_one: {
      name: "Christoforo Shortall",
      phone: "205-680-6374",
      email: "cshortall0@cdbaby.com",
      consent: true,
    },
    parent_two: null,
    student: true,
  },
  {
    _id: 5,
    name: "Andrey Pressnell",
    current_school: "North Bengal University",
    current_grade: 1,
    current_gpa: 1.49,
    eigth_grade_school: "didactic",
    personal_email: "apressnell4@barnesandnoble.com",
    cell_phone: "408-799-4418",
    home_phone: "508-705-8273",
    street: "028 Warbler Place",
    city: "San Jose",
    state: "California",
    zipcode: "95113",
    birthdate: "12/22/1993",
    gender: "Male",
    race: "Tohono O'Odham",
    ethnicity: "White",
    student_consent: true,
    dietary_restrictions: null,
    health_restrictions: null,
    parent_one: {
      name: "Christoforo Shortall",
      phone: "205-680-6374",
      email: "cshortall0@cdbaby.com",
      consent: true,
    },
    parent_two: null,
    student: true,
  },
  {
    _id: 6,
    name: "Eben Edden",
    current_school: "Ege University",
    current_grade: 4,
    current_gpa: 1.19,
    eigth_grade_school: "capacity",
    personal_email: "eedden5@mozilla.org",
    cell_phone: "405-681-2097",
    home_phone: "904-446-4824",
    street: "1 Fisk Junction",
    city: "Oklahoma City",
    state: "Oklahoma",
    zipcode: "73142",
    birthdate: "1/20/1994",
    gender: "Male",
    race: "Blackfeet",
    ethnicity: "Guatemalan",
    student_consent: false,
    dietary_restrictions: "INSTANT Hand Sanitizer with Moisturizers All In One",
    health_restrictions: null,
    parent_one: {
      name: "Christoforo Shortall",
      phone: "205-680-6374",
      email: "cshortall0@cdbaby.com",
      consent: true,
    },
    parent_two: null,
    student: true,
  },
  {
    _id: 7,
    name: "Donia McCreery",
    current_school: "KBU International College",
    current_grade: 1,
    current_gpa: 1.63,
    eigth_grade_school: "Mandatory",
    personal_email: "dmccreery6@ycombinator.com",
    cell_phone: "208-605-0615",
    home_phone: "972-331-0199",
    street: "6 Waywood Court",
    city: "Boise",
    state: "Idaho",
    zipcode: "83716",
    birthdate: "3/20/1996",
    gender: "Female",
    race: "Nicaraguan",
    ethnicity: "Hmong",
    student_consent: false,
    dietary_restrictions: "Amiodarone Hydrochloride",
    health_restrictions: null,
    parent_one: {
      name: "Christoforo Shortall",
      phone: "205-680-6374",
      email: "cshortall0@cdbaby.com",
      consent: true,
    },
    parent_two: null,
    student: true,
  },
  {
    _id: 8,
    name: "Crawford Sweeting",
    current_school: "Mercer University, Cecil B. Day Campus",
    current_grade: 4,
    current_gpa: 3.12,
    eigth_grade_school: "modular",
    personal_email: "csweeting7@squarespace.com",
    cell_phone: "386-316-0387",
    home_phone: "508-367-9110",
    street: "38 3rd Center",
    city: "Daytona Beach",
    state: "Florida",
    zipcode: "32123",
    birthdate: "8/12/1996",
    gender: "Male",
    race: "Spaniard",
    ethnicity: "Chinese",
    student_consent: true,
    dietary_restrictions: "Leflunomide",
    health_restrictions: "Fresh Herbs Antibacterial Hand Wash",
    parent_one: {
      name: "Christoforo Shortall",
      phone: "205-680-6374",
      email: "cshortall0@cdbaby.com",
      consent: true,
    },
    parent_two: null,
    student: true,
  },
  {
    _id: 9,
    name: "Niles Borrows",
    current_school: "Universität Mozarteum Salzburg",
    current_grade: 2,
    current_gpa: 2.18,
    eigth_grade_school: "Centralized",
    personal_email: "nborrows8@guardian.co.uk",
    cell_phone: "612-288-1994",
    home_phone: "516-880-2749",
    street: "3 Welch Center",
    city: "Minneapolis",
    state: "Minnesota",
    zipcode: "55448",
    birthdate: "12/11/1990",
    gender: "Male",
    race: "Yaqui",
    ethnicity: "Potawatomi",
    student_consent: false,
    dietary_restrictions: null,
    health_restrictions: "Neutrogena Nourishing Eye Quad",
    parent_one: {
      name: "Christoforo Shortall",
      phone: "205-680-6374",
      email: "cshortall0@cdbaby.com",
      consent: true,
    },
    parent_two: null,
    student: true,
  },
  {
    _id: 10,
    name: "Gasper Corroyer",
    current_school: "L'Université de l'Entreprise",
    current_grade: 2,
    current_gpa: 2.51,
    eigth_grade_school: "regional",
    personal_email: "gcorroyer9@arizona.edu",
    cell_phone: "971-239-8943",
    home_phone: "916-691-0089",
    street: "6008 Commercial Park",
    city: "Portland",
    state: "Oregon",
    zipcode: "97201",
    birthdate: "9/5/1993",
    gender: "Male",
    race: "Cheyenne",
    ethnicity: "Native Hawaiian",
    student_consent: true,
    dietary_restrictions: null,
    health_restrictions: null,
    parent_one: {
      name: "Christoforo Shortall",
      phone: "205-680-6374",
      email: "cshortall0@cdbaby.com",
      consent: true,
    },
    parent_two: null,
    student: true,
  },
  {
    _id: 11,
    name: "Jo-ann Baggott",
    current_school: "Scandinavian Art and Business Institute",
    current_grade: 3,
    current_gpa: 2.73,
    eigth_grade_school: "encompassing",
    personal_email: "jbaggotta@tripadvisor.com",
    cell_phone: "816-711-1670",
    home_phone: "502-564-3782",
    street: "9 Norway Maple Circle",
    city: "Kansas City",
    state: "Missouri",
    zipcode: "64142",
    birthdate: "12/22/1994",
    gender: "Female",
    race: "Melanesian",
    ethnicity: "Iroquois",
    student_consent: true,
    dietary_restrictions: "Amlodipine besylate",
    health_restrictions: null,
    parent_one: {
      name: "Christoforo Shortall",
      phone: "205-680-6374",
      email: "cshortall0@cdbaby.com",
      consent: true,
    },
    parent_two: null,
    student: true,
  },
  {
    _id: 12,
    name: "Burt Dunk",
    current_school: "University of Texas at Austin",
    current_grade: 3,
    current_gpa: 3.42,
    eigth_grade_school: "collaboration",
    personal_email: "bdunkb@dion.ne.jp",
    cell_phone: "218-516-4863",
    home_phone: "916-614-4095",
    street: "5586 Village Plaza",
    city: "Duluth",
    state: "Minnesota",
    zipcode: "55805",
    birthdate: "10/18/1992",
    gender: "Male",
    race: "Ottawa",
    ethnicity: "Sioux",
    student_consent: false,
    dietary_restrictions: null,
    health_restrictions: "Cefadroxil",
    parent_one: {
      name: "Christoforo Shortall",
      phone: "205-680-6374",
      email: "cshortall0@cdbaby.com",
      consent: true,
    },
    parent_two: null,
    student: true,
  },
  {
    _id: 13,
    name: "Vlad Benion",
    current_school: "Universitas Muhammadiyah Malang",
    current_grade: 2,
    current_gpa: 3.42,
    eigth_grade_school: "system engine",
    personal_email: "vbenionc@ucoz.ru",
    cell_phone: "317-750-2211",
    home_phone: "323-551-4107",
    street: "76930 Thierer Lane",
    city: "Indianapolis",
    state: "Indiana",
    zipcode: "46266",
    birthdate: "10/17/1991",
    gender: "Male",
    race: "Shoshone",
    ethnicity: "Puget Sound Salish",
    student_consent: true,
    dietary_restrictions: "Sinus Buster Mild Formula",
    health_restrictions: null,
    parent_one: {
      name: "Christoforo Shortall",
      phone: "205-680-6374",
      email: "cshortall0@cdbaby.com",
      consent: true,
    },
    parent_two: null,
    student: true,
  },
  {
    _id: 14,
    name: "Osbourn Jacmar",
    current_school: "Pontifica Università Gregoriana",
    current_grade: 3,
    current_gpa: 3.09,
    eigth_grade_school: "even-keeled",
    personal_email: "ojacmard@privacy.gov.au",
    cell_phone: "212-119-4660",
    home_phone: "410-472-3524",
    street: "1962 Steensland Street",
    city: "New York City",
    state: "New York",
    zipcode: "10131",
    birthdate: "12/8/1992",
    gender: "Male",
    race: "Creek",
    ethnicity: "Micronesian",
    student_consent: true,
    dietary_restrictions: "Gemcitabine",
    health_restrictions: null,
    parent_one: {
      name: "Christoforo Shortall",
      phone: "205-680-6374",
      email: "cshortall0@cdbaby.com",
      consent: true,
    },
    parent_two: null,
    student: true,
  },
  {
    _id: 15,
    name: "Hedi Rushe",
    current_school: "Universidade Católica de Petrópolis",
    current_grade: 1,
    current_gpa: 3.15,
    eigth_grade_school: "attitude-oriented",
    personal_email: "hrushee@loc.gov",
    cell_phone: "316-628-9429",
    home_phone: "978-394-8559",
    street: "87 Huxley Lane",
    city: "Wichita",
    state: "Kansas",
    zipcode: "67215",
    birthdate: "4/3/1994",
    gender: "Female",
    race: "Vietnamese",
    ethnicity: "Ute",
    student_consent: false,
    dietary_restrictions: null,
    health_restrictions: "Nighttime Sleep-Aid",
    parent_one: {
      name: "Christoforo Shortall",
      phone: "205-680-6374",
      email: "cshortall0@cdbaby.com",
      consent: true,
    },
    parent_two: null,
    student: true,
  },
  //mentors
  {
    _id: 16,
    name: "Giacinta Salzburg",
    eigth_grade_school: "Public-key",
    personal_email: "gsalzburg0@webmd.com",
    cell_phone: "447-749-1748",
    birthdate: "1/29/1994",
    dietary_restrictions: null,
    health_restrictions: null,
    stims_registration: false,
    volunteer_hadbook: false,
    tb_assessment: true,
    voluntary_waiver: false,
    live_scan: true,
    dv_handbook_signature: false,
    hours: {
      fall: {
        total: 100,
        weeks: [10, 10, 10, 10, 10],
      },
      spring: {
        total: 120,
        weeks: [10, 10, 10, 10, 10, 20, 23],
      },
    },
    student: false,
  },
  {
    _id: 17,
    name: "Corilla Bratcher",
    eigth_grade_school: "open architecture",
    personal_email: "cbratcher1@chicagotribune.com",
    cell_phone: "119-726-3598",
    birthdate: "5/21/1993",
    dietary_restrictions: null,
    health_restrictions: null,
    stims_registration: false,
    volunteer_hadbook: true,
    tb_assessment: false,
    voluntary_waiver: false,
    live_scan: false,
    dv_handbook_signature: true,
    hours: {
      fall: {
        total: 100,
        weeks: [10, 10, 10, 10, 10],
      },
      spring: {
        total: 120,
        weeks: [10, 10, 10, 10, 10, 20, 23],
      },
    },
    student: false,
  },
  {
    _id: 18,
    name: "Wylma Gilsthorpe",
    eigth_grade_school: "Reduced",
    personal_email: "wgilsthorpe2@slideshare.net",
    cell_phone: "402-248-7254",
    birthdate: "2/11/1996",
    dietary_restrictions: null,
    health_restrictions: "Geodon",
    stims_registration: true,
    volunteer_hadbook: false,
    tb_assessment: true,
    voluntary_waiver: false,
    live_scan: true,
    dv_handbook_signature: false,
    hours: {
      fall: {
        total: 100,
        weeks: [10, 10, 10, 10, 10],
      },
      spring: {
        total: 120,
        weeks: [10, 10, 10, 10, 10, 20, 23],
      },
    },
    student: false,
  },
  {
    _id: 19,
    name: "Dre Scoffins",
    eigth_grade_school: "archive",
    personal_email: "dscoffins3@java.com",
    cell_phone: "342-805-7713",
    birthdate: "3/29/1991",
    dietary_restrictions: "PROVENCE FOUNDATION",
    health_restrictions: null,
    stims_registration: false,
    volunteer_hadbook: false,
    tb_assessment: false,
    voluntary_waiver: false,
    live_scan: false,
    dv_handbook_signature: false,
    hours: {
      fall: {
        total: 100,
        weeks: [10, 10, 10, 10, 10],
      },
      spring: {
        total: 120,
        weeks: [10, 10, 10, 10, 10, 20, 23],
      },
    },
    student: false,
  },
  {
    _id: 20,
    name: "Martguerita Matteoli",
    eigth_grade_school: "Progressive",
    personal_email: "mmatteoli4@free.fr",
    cell_phone: "896-714-7238",
    birthdate: "11/9/1990",
    dietary_restrictions: null,
    health_restrictions: "CareOne Pain Relief",
    stims_registration: true,
    volunteer_hadbook: true,
    tb_assessment: true,
    voluntary_waiver: true,
    live_scan: false,
    dv_handbook_signature: false,
    hours: {
      fall: {
        total: 100,
        weeks: [10, 10, 10, 10, 10],
      },
      spring: {
        total: 120,
        weeks: [10, 10, 10, 10, 10, 20, 23],
      },
    },
    student: false,
  },
];

registeredEvents = [
  {
    _id: 1,
    name: "FLL Tournament - Winward High School",
    date: "11/13/2016",
    time: "6 AM - 4PM",
    role: "Referee",
  },
  {
    _id: 2,
    name: "FLL Tournament - Whittier High School",
    date: "11/12/2016",
    time: "6 AM - 4PM",
    role: "Referee",
  },
  {
    _id: 3,
    name: "FLL Tournament - Parras Middle School",
    date: "11/5/2016",
    time: "6 AM - 4PM",
    role: "Referee",
  },
  {
    _id: 4,
    name: "FLL Tournament - WISH Charter School",
    date: "11/6/2016",
    time: "6 AM - 4PM",
    role: "Referee",
  },
];

window.onload = pageSetup();
